version: '3'

services:
    backend:
        container_name: backend
        build: ./backend
        volumes: 
            - ./backend:/usr/src/app
            - backend_node_modules:/usr/src/app/node_modules
        expose:
            - 3001
        depends_on: 
            - db
        networks: 
            - net
        stdin_open: true
        tty: true
    
    db:
        container_name: database
        build: .
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=database_name
        networks:
            - net

    frontend:
        container_name: frontend
        build: ./frontend
        volumes:
            - ./frontend:/usr/src/app
            - frontend_node_modules:/usr/src/app/node_modules
        expose:
            - 3000
        environment: 
            - CHOKIDAR_USEPOLLING=true
        networks:
            - net
        stdin_open: true
        tty: true

    nginx:
        container_name: nginx
        build: ./nginx
        ports: 
            - 80:80
        networks:
            - net

volumes:
    backend_node_modules:
    postgres_data:
    frontend_node_modules:

networks:
    net: